spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/bigtom
  username: root
  password: mysql
  
 jpa:
  show-sql: true
  properties: 
   hibernate: 
    dialect: org.hibernate.dialect.MySQL5Dialect